language: java
install: true
before_install:
- cd Quelea
- chmod +x gradlew
jdk:
- oraclejdk8
script:
- "./gradlew dist --scan"
deploy:
  provider: releases
  api_key:
    secure: j2NVhTT+Z7b5VF0a40p+np4Kc2MAd4L505Zz/ID3TIytLgl2tbNkU5sbrj0qzrweq19FrxtOMsnmbYrCx3hIVw0Q2VKaxXOKvX/e0Qm9Sb6z0Bc8p4mwzXA2tuNyLlKCMZF1ePcNz5aEoxlDhoT0gtsBR18uRyndZGF44X/9HudkEdFFsruUoJDVk9cW+0QbNTTf/xqe7zaZhfIZHqLDXOulApdanwmWtrns782PtLtF91vKUaEZ53VGD7KkZJahpvxRKvZwICvtKyVE6Afi3Hze49d76nvB0GG6sC9OK4/gpZR7RChB8IsOTyx+5Z4zNXdkxlBS6LqBdCcq7Fj16yzay9DT1eCxTTdsQR1wuA3KWwHS1xWYaI5latc+SC+2PpaZ4mgVUIpOAA+6qMDhyxKC5xRFJi87zsfRG67CWJNZ8w8kjHSNvSw/8bndZm7ZAFaVM+dazjSTSWHzePIyiz4bxezwI9sftHaL6aQ2XzvQkIBMX3HJtqKFX/6A5Qb+8qfmJjx3aCU/s0Vo1gMtPjuPjCQph3d/Bu3gdo1oquzgw2d9d7NEibQAIPmrfnfNCxyg0vgRzNaY+AQthngCrtlB/aKqs6OwjQYLjUXiLIpMUZXAle3H7mIwcAJCS6kY1n0njIdkpfQIIvgWqzeak0oCKBKQVaaAuiLLx7zG+tY=
  file_glob: true
  file: Quelea/dist/standalone/*
  skip_cleanup: true
  prerelease: true
