language: java
install: true
before_install:
- cd Quelea
- chmod +x gradlew
jdk:
- oraclejdk8
script:
- "./gradlew dist --scan"
deploy:
  provider: releases
  api_key:
    secure: "dI5Ra6jEkioaEQT+pEWQmqHaJQmdBtO+mJNLpLrFaj7op9cKg8VzoSDrDd+tV1Uoi0CkPCi3OqdCy7o+/a7p8fKMG7A21S5jzEDXUAwlnr/uaoz8jaDlKVtqsAROYbqWRpxnO+uxISYjm7cd0r0n46N0jfNgW0rJO0hRDs0IjhMHICr8J6KsfZBH6lw/cScAgeL9VVTa4zfAO/zNo0Tlr0eIcAhQd2d3+eyIV+q/zzjmohBwIWecsNC0z9OuFk04DxSP1kcCDiJ9l2nWeZIWWEI1yN0beIZiPX8znT8xC9JWIKfqjytmLahmA3+ECj6sQeMlUeXQmsxff4P2LQm4Jdvu+08b4o5G4ZKSWn/yMja19RD37lHvp72T4wVKTfZwFq2O/GS4fIfBkr4Xo8dVdhAEIcp9Ns6dznWm5ko4lYvX5pkTwMPV7bCon1wcVf7WrBn9CkHSWeRsy/hl8ghnUnkxF/MrYRCLMKGuuD2jMqMGhTKfC3tB2LzKZ9Gq4zYNM2AigCM3i+2kZ25lav8NfyxTxwGZ9XQC9hHOxZ7Gp9W5KMD9IYLtApWX1yhMICUiDfrOL1UF3mLELBS5do6TmDhFZ1wWVyzYSUn7fqQRV+W6CzmonMXrJzRROl9WvNXC2t63TMBFevd/sohZA8TvAAq/35gTxEru54qLaOuMezc="
  file_glob: true
  file: 'Quelea/dist/standalone/*'
  skip_cleanup: true
  prerelease: true
