language: java
install: true
before_install:
- cd Quelea
- chmod +x gradlew
jdk:
- oraclejdk8
script:
- "./gradlew dist --scan"
deploy:
  provider: releases
  api_key:
    secure: xAS9jZwUQrRU+Wvi4fBJ9bNEctzUdjLSojzkrNKeofYIzmBA/HjjvCRfeClaR8Y3bjCpMxMdjGifaaWCrOPTCUb8z4NkdsPfA0gEVhrfGK+hVskxHLwLtPXQYcU68CKmJ1UsKKnfQRotwKDqoDd1C9cYla1gUPI+W3LsivKyAfzExD7Gf5igNVpW7MZOiKfFZlW23Q4n6tJY8XMp68kXA69kauXEHtiyJxx9XgbKUe8s4Uw/2y8WmwnsrzMs8o8j2Q+ZKPvLexS1JwlAWhMVvnkZjG9/vKkLK67t/rF6V+cRk3SvlRCjP6kgCRmsFDygasa4KoswAFA10Rs+PqaamdMUaNKdQ4IEwtnyN1FwfaXKDyNc4npc/+sAlUMA0pFHG+0A4E+cmJBJGGYhGAKVR6XC+1ER6Kc3wxEzAmV9tvbWMmDF2JOjH3dGM6myVJjEj7j2LV3CLRzK+PcoKt6LPy5Q/PyASxIUf61GFYE5z3lpnoELrE2YVwM9aseZUqGBtaDNeXKl/fbvl+ZjiOhjC5xNDKchHPnZ/4K4nOI3h8i9KZEFecoaCdcSob0R/VxjcllrSY+6f/Ephj3Kk7W508fwYaDfZYP1OCOfYISOdAh3DVIOSLPlMdqViltWP1Zv9SyYF0ptdiVOAOMRvlH+OL8HDMhzlFLza3mkI67o0us=
  file_glob: true
  file: 'Quelea/dist/standalone/*'
  skip_cleanup: true
  prerelease: true
