if: tag IS blank
language: java
install: true
before_install:
- cd Quelea
- chmod +x gradlew
jdk:
- oraclejdk8
script:
- "./gradlew dist --scan"
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
- git push -q https://${GH_TOKEN}@github.com/quelea-projection/Quelea --tags
- ls -R
deploy:
  provider: releases
  api_key:
    secure: j2NVhTT+Z7b5VF0a40p+np4Kc2MAd4L505Zz/ID3TIytLgl2tbNkU5sbrj0qzrweq19FrxtOMsnmbYrCx3hIVw0Q2VKaxXOKvX/e0Qm9Sb6z0Bc8p4mwzXA2tuNyLlKCMZF1ePcNz5aEoxlDhoT0gtsBR18uRyndZGF44X/9HudkEdFFsruUoJDVk9cW+0QbNTTf/xqe7zaZhfIZHqLDXOulApdanwmWtrns782PtLtF91vKUaEZ53VGD7KkZJahpvxRKvZwICvtKyVE6Afi3Hze49d76nvB0GG6sC9OK4/gpZR7RChB8IsOTyx+5Z4zNXdkxlBS6LqBdCcq7Fj16yzay9DT1eCxTTdsQR1wuA3KWwHS1xWYaI5latc+SC+2PpaZ4mgVUIpOAA+6qMDhyxKC5xRFJi87zsfRG67CWJNZ8w8kjHSNvSw/8bndZm7ZAFaVM+dazjSTSWHzePIyiz4bxezwI9sftHaL6aQ2XzvQkIBMX3HJtqKFX/6A5Qb+8qfmJjx3aCU/s0Vo1gMtPjuPjCQph3d/Bu3gdo1oquzgw2d9d7NEibQAIPmrfnfNCxyg0vgRzNaY+AQthngCrtlB/aKqs6OwjQYLjUXiLIpMUZXAle3H7mIwcAJCS6kY1n0njIdkpfQIIvgWqzeak0oCKBKQVaaAuiLLx7zG+tY=
  file_glob: true
  file: dist/standalone/*
  skip_cleanup: true
  prerelease: true
env:
  global:
    secure: B2CmIfRyqbeM0xDmxsKqfhvbx4Gr2sSrG9ZtkGWs0HkwmPtoWqqF6bibdj4nSArqTxaNGoHvlGuv2Psw7YK3cbGErHhAlDBzf9QiHkSYXN0NlYw3kH9k+O2h5lR7H8RwTXFxrTaoQSaXXpKQTytYDFh/fJEakIj7+tWTHa6WPDN0FmOjEvcij50WQfItW1/G3evQ5/AvbKF8DI6U9jNu66PEyDMVoTE4aLedoL7CTZRiA+tllttmIgy5z9ONzCr/hqamNfVz71/t+H7UkY2Z0WhRYydpp+6ck53uNzMwwBcPB4hz4Z1bvA7py78wewRTo+8TGWjRG5qr6DWY10sm9s60FU4E8m53gpA+rTPOTMckULFDZ9A7rYyFNTnKWf+3tvO98VoFt5XI9c329rC3stu1guhjTiPNE+tMJ/q762tVBFh9C9o/77HqyJDNbZo4rifDus2Sb4JlJEQdFlhb6oVJ2nz/Z+6qPbGbvjjvUwoul3lREc2D5VSssgdVJ7gTP9UwQhOqCGaYqhJiW6lKTuIDyzZz+Twp3WDTqbmTnu/Yxx6ieHkSDFFGjWtJrrA2qjrwwqjcUnzt2G76GfWiRNVXdRWd8FkCcY/pykWd4ZQZHSSdcKgANYYcTnbVFfrrODYS2yRWX7c2O4ysnyH3B3KY4P7Csq0Eg36RcNTysPE=
