sudo: required
if: tag IS blank
language: java
dist: trusty
git:
  lfs_skip_smudge: true
install:
  - git lfs pull
addons:
  apt:
    packages:
    - wine
    - xvfb
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - .git/lfs
before_install:
  - cd Quelea
  - chmod +x gradlew
  - chmod +x build-install.sh
  - wget http://files.jrsoftware.org/is/5/innosetup-5.6.1.exe
  - wineboot --update
  - Xvfb :0 -screen 0 1024x768x16 &
  - DISPLAY=:0.0 wine innosetup-5.6.1.exe /VERYSILENT /SUPPRESSMSGBOXES
jdk:
  - oraclejdk9
script:
  - "./gradlew -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean dist --scan"
  - PREVDIR="$(pwd)"
  - cd $(mktemp -d)
  - git clone https://quelea-bot:${QBOT_TOKEN}@github.com/quelea-projection/quelea-projection.github.io.git ./repo
  - cp $PREVDIR/dist/missinglabels.js repo/lang/
  - cd repo
  - ls -l lang/
  - git add lang/missinglabels.js
  - git commit -m "Update missing labels file" || ls -l
  - git push || echo "PR build, no problem"
  - cd $PREVDIR
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=CI-RELEASE
  - export RELEASE_DESCRIPTION="**CI Build $TRAVIS_BUILD_NUMBER - not to be used in production.**<br/>Quelea is also distributed as a Linux snap package. To install it, make sure snap is installed then run:<pre>sudo snap install --edge quelea</pre><h3>SHA256 hashes:</h3><table><tr><th>Windows x64</th><td>$(sha256sum dist/standalone/quelea-CI-UNSTABLE-x64-windows-install.exe | cut -d ' ' -f 1)</td></tr><tr><th>Crossplatform</th><td>$(sha256sum dist/standalone/quelea-CI-UNSTABLE-crossplatform-install.jar | cut -d ' ' -f 1 )</td></tr><tr><th>Mac</th><td>$(sha256sum dist/standalone/quelea-CI-UNSTABLE-mac.zip | cut -d ' ' -f 1 )</td></tr></table>"
  - git tag -f $GIT_TAG -a -m "CI Build $TRAVIS_BUILD_NUMBER - not to be used in production."
  - git push --delete https://quelea-bot:${QBOT_TOKEN}@github.com/quelea-projection/Quelea CI-RELEASE
  - git push -q https://quelea-bot:${QBOT_TOKEN}@github.com/quelea-projection/Quelea --tags
deploy:
  - provider: releases
    api_key:
      secure: UvpF9ALbHGsIFQv1SzH240WjdS6cZ/+sCbuGirMgtcIrtHCKd7p7ZfdGWRAtO4qxIY5Lu3QRuoT+oLMC1gJyF/pAq7CO53SDyJBwfACcQWrz1n5X5XJZngKwZGDVhVzTCqFWLpi1K/DWDj5jGv3kPj8RprZXZbSKqgQYXd2ZTe98c1irm45OY+IOJjlYd3AsWxjgseMSozj1t3iGzp0Y1b87OeV9494XtvT39d5t7Mozq2cP77gPFfQGWS8I4kTlAJtOK27ghkkyIciYTWln7+qZXSL1/wXQ09f4/yG1LFpsm1yaBn4qud8lxYaJXGVBGW9tH84l3v1+QUdD5aCX7kNoLbxbR388KwJPLshPw0Pu+wUPywiI3GDXUYFyotGEiy701qPSMrV/7N9TdLpeYaG5MRmJm81X9B8AY9soFpdpoB5XPz6XSxw1Tu4X+Sfccwn++q0hiLEW5KxA8ItF8LKVOhTDW3qlO440thPthJiBr+jzEUCGX6pxjFZqd788SfGFaqI03JsBrDoDg34nOqoOvoSi5CqkSemLYJVkG8euXZGcDVbDOpT9YH92Nv56NRKxsoEgQqjXR7XQR1MIhFmidBs6+BJ21hbAwy/WMPMDso8hGz306j3iWesv1DquYP4jo7u3LHhAYwLrttWcYlcqz+91sJfdeFPWNnIx3vI=
    file_glob: true
    file: dist/standalone/*
    skip_cleanup: true
    prerelease: true
    overwrite: true
    body: $RELEASE_DESCRIPTION
    target_commitish: $TRAVIS_COMMIT
env:
  global:
    secure: B2CmIfRyqbeM0xDmxsKqfhvbx4Gr2sSrG9ZtkGWs0HkwmPtoWqqF6bibdj4nSArqTxaNGoHvlGuv2Psw7YK3cbGErHhAlDBzf9QiHkSYXN0NlYw3kH9k+O2h5lR7H8RwTXFxrTaoQSaXXpKQTytYDFh/fJEakIj7+tWTHa6WPDN0FmOjEvcij50WQfItW1/G3evQ5/AvbKF8DI6U9jNu66PEyDMVoTE4aLedoL7CTZRiA+tllttmIgy5z9ONzCr/hqamNfVz71/t+H7UkY2Z0WhRYydpp+6ck53uNzMwwBcPB4hz4Z1bvA7py78wewRTo+8TGWjRG5qr6DWY10sm9s60FU4E8m53gpA+rTPOTMckULFDZ9A7rYyFNTnKWf+3tvO98VoFt5XI9c329rC3stu1guhjTiPNE+tMJ/q762tVBFh9C9o/77HqyJDNbZo4rifDus2Sb4JlJEQdFlhb6oVJ2nz/Z+6qPbGbvjjvUwoul3lREc2D5VSssgdVJ7gTP9UwQhOqCGaYqhJiW6lKTuIDyzZz+Twp3WDTqbmTnu/Yxx6ieHkSDFFGjWtJrrA2qjrwwqjcUnzt2G76GfWiRNVXdRWd8FkCcY/pykWd4ZQZHSSdcKgANYYcTnbVFfrrODYS2yRWX7c2O4ysnyH3B3KY4P7Csq0Eg36RcNTysPE=
    
