language: java
install: true
before_install:
- cd Quelea
- chmod +x gradlew
jdk:
- oraclejdk8
script:
- "./gradlew dist --scan"
deploy:
  provider: releases
  api_key:
    secure: "N3wnugmNTr/2rD9hs6cKDKbR5tnqeKCrnaMPe34bhUPUSppyrPO0pLVZx65c2J3NZl6JJ0Npks+zFavpxr80t82rMnjGVijK0PIPj3kMgSEqeZg3PBUagaHi6vOW8Rwp/7AnCup2zGS9Do0pL0dxHQ+z/QtcgG9GPA0K0byKYtB+tWPR5lsVl7SWa48H7QSBAoaIDIabWQ4XYwS3gjj0ZB/XLckN3U5muMBIA3ZaDZBVJ8l2tSyIm8+1VFf0oXdW3V5tW14PFlpqPSYJMpIW+GQ47Mt8W5EGM+uGpgqyRH2qaFUf9KKif4KIY6MVFDVnqOczyMQSCI/2Qqve1yXFSFyF2c+cWtp3lLBWIp3V0+5ZPtVzFx5xX0WHQVUOoIXUWTF1xxJGd9fxpb7UGOi04Q9JYWjaWpbA5z0i4oJS4+/mNbWwFrfsNnEtQfb/USpgugprZXbYaZxmWhc8QfTBHL3XbLbZHAYMubKLNVIlIfu871/xmcVB2uh7wVdA6LmMmm4kLnP9w7meyWsoMK+nmYYpBWBMwoYGfDyaBOE8WVudj84M6e6RmeUAPc4gqtg47LJdUSaBmfY6A8mYf9eK5Mf63QDS+bfyLiVbMCBF72lpROks2CvWPA2Jz16Y+02VegecdT/Bdx/t+lwzPgUzhv0L6k6shv7sRNu2LDXXNBg="
  file_glob: true
  file: 'Quelea/dist/standalone/*'
  skip_cleanup: true
  prerelease: true
