name: quelea
version: '2019.0' 
summary: Church projection
description: |
  Quelea is a free and open source software application that projects
  multimedia content in your church service.

confinement: strict

environment:
    JAVA_HOME: $SNAP/jar/linjre64
    PATH: $SNAP/jar/linjre64/bin:$PATH
    
architectures:
  - build-on: amd64

apps:
  quelea:
    command: sh $SNAP/jar/launch.sh
    plugs: [home, network, network-bind, x11, wayland, unity7, opengl, optical-drive, alsa, pulseaudio, desktop, desktop-legacy, removable-media]

parts:
  quelea:
    plugin: nil
    source: Quelea
    build-packages: [gradle]
    stage-packages: [vlc]
    build: wget https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/201807101745/OpenJDK10_x64_Linux_201807101745.tar.gz && tar -xzf OpenJDK10_x64_Linux_201807101745.tar.gz && ls -l jdk-10.0.1+10 && gradle -Dorg.gradle.java.home=jdk-10.0.1+10 -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean jar copyToDist dist
    after: [desktop-gtk3]
