name: quelea
version: '2019.0' 
summary: Church projection
description: |
  Quelea is a free and open source software application that projects
  multimedia content in your church service.

confinement: strict

environment:
    JAVA_HOME: $SNAP/jar/linjre64
    PATH: $SNAP/jar/linjre64/bin:$PATH
    
architectures:
  - build-on: amd64

apps:
  quelea:
    command: sh $SNAP/jar/launch.sh
    plugs: [home, network, network-bind, x11, wayland, unity7, opengl, optical-drive, alsa, pulseaudio, desktop, desktop-legacy, removable-media]

parts:
  quelea:
    plugin: nil
    source: Quelea
    build-packages: [gradle]
    stage-packages: [vlc]
    build: unzip bundlejre/linjre64 && ls -l && ls -l bundlejre && gradle -Dorg.gradle.java.home=linjre64 -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean jar copyToDist dist
    after: [desktop-gtk3]
