
  name: quelea
  version: '0.1'
  summary: Church projection software
  description: |
    Project lyrics, videos, images, powerpoint presentations and more during your church service.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  quelea:
    command: java -jar Quelea.jar

parts:
  quelea:
    plugin: gradle
    source: .
    build: |
      export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
      gradle -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean dist
    install: |
      unzip dist/quelea-snap.zip -d $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - unzip
      - openjdk-8-jdk
  
