name: quelea
version: '2019.0' 
summary: Church projection
description: |
  Quelea is a free and open source software application that projects
  multimedia content in your church service.

confinement: strict

environment:
    JAVA_HOME: $SNAP/jar/linjre64
    PATH: $SNAP/jar/linjre64/bin:$PATH
    
architectures:
  - build-on: amd64

apps:
  quelea:
    command: sh $SNAP/jar/launch.sh
    plugs: [home, network, network-bind, x11, wayland, unity7, opengl, optical-drive, alsa, pulseaudio, desktop, desktop-legacy, removable-media]

parts:
  quelea:
    plugin: gradle
    source: Quelea
    stage-packages: [vlc]
    gradle-options: [-Dorg.gradle.java.home=$SNAP/usr/lib/jvm/java-9-openjdk-amd64, -Dnightly=true, -Dversionsuffix=CI-UNSTABLE, clean, jar, copyToDist]
    gradle-output-dir: 'dist'
    after: [desktop-gtk3]
