name: quelea
version: '2019.0' 
summary: Church projection
description: |
  Quelea is a free and open source software application that projects
  multimedia content in your church service.

confinement: devmode

apps:
  quelea:
    command: desktop-launch $SNAP/quelea/launch.sh

parts:
  quelea:
    plugin: gradle
    source: Quelea
    stage-packages: [default-jre, openjfx]
    gradle-options: [-Dnightly=true, -Dversionsuffix=CI-UNSTABLE, clean, jar]
    gradle-output-dir: 'build'
