name: quelea
version: '2019.0' 
summary: Church projection
description: |
  Quelea is a free and open source software application that projects
  multimedia content in your church service.

confinement: strict

environment:
    JAVA_HOME: $SNAP/jar/linjre64
    PATH: $SNAP/jar/linjre64/bin:$PATH
    
architectures:
  - build-on: amd64

apps:
  quelea:
    command: sh $SNAP/jar/launch.sh
    plugs: [home, network, network-bind, x11, wayland, unity7, opengl, optical-drive, alsa, pulseaudio, desktop, desktop-legacy, removable-media]

parts:
  quelea:
    plugin: nil
    source: Quelea
    build-packages: [gradle, wget, tar]
    stage-packages: [vlc]
    build: export JAVA_OPTS="-Dhttp.proxyHost=10.10.10.1 -Dhttp.proxyPort=8222 -Dhttps.proxyHost=10.10.10.1 -Dhttps.proxyPort=8222" && gradle wrapper --gradle-version 4.9 && wget -q https://github.com/AdoptOpenJDK/openjdk10-releases/releases/download/201807101745/OpenJDK10_x64_Linux_201807101745.tar.gz && tar -xzf OpenJDK10_x64_Linux_201807101745.tar.gz && wget -q https://download.java.net/java/early_access/openjfx11/20/binaries/openjfx-11-ea+20_linux-x64_bin-jmods.zip && unzip openjfx-11-ea+20_linux-x64_bin-jmods.zip 'javafx-jmods-11/*' -d jdk-10.0.1+10/jmods && ls -l && ls -l jdk-10.0.1+10/jmods && ls -l jdk-10.0.1+10 && ./gradlew -Dhttp.proxyHost=10.10.10.1 -Dhttp.proxyPort=8222 -Dhttps.proxyHost=10.10.10.1 -Dhttps.proxyPort=8222 -Dorg.gradle.java.home=jdk-10.0.1+10 -Dnightly=true -Dversionsuffix=CI-UNSTABLE clean jar copyToDist dist --stacktrace
    after: [desktop-gtk3]
